# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-22 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=20)),
                ('doors', models.IntegerField(default=3)),
                ('lot_number', models.IntegerField()),
            ],
        ),
    ]
